import "./globals.css";
import { Inter } from "next/font/google";
import NextAuthProvider from "components/NextAuthProvider/NextAuthProvider";
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <NextAuthProvider session={session}>
        <body className={inter.className}>{children}</body>
      </NextAuthProvider>
    </html>
  );
}
