import "./globals.css";
import "./variables.css";
import { Providers } from "./providers";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import Navigation from "@components/Navigation/Navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // interactiveWidget="resizes-content"
};

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default async function RootLayout({ children }) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers session={session}>
          {children}
          <Navigation />
        </Providers>
      </body>
    </html>
  );
}
